# build matrix consists of different versions of Sage on different platforms.
# the versions are obtained via tarball download since Sage is not a supported
# "language" in TravisCI
#
# choice of Sage version is determined via environment variables
#
env:
  global:
    - SAGE=${HOME}/SageMath/sage

matrix:
  include:
    - os: linux
      env:
        - SAGE_TARBALL=sage-8.0-Ubuntu_14.04-x86_64.tar.bz2
        - SAGE_SERVER=http://mirrors.mit.edu/sage/linux/64bit
      dist: trusty
    - os: osx
      env:
        - SAGE_TARBALL=sage-8.0-OSX_10.12.6-x86_64.tar.bz2
        - SAGE_SERVER=ftp://ftp.fu-berlin.de/unix/misc/sage/osx/intel
      osx_image: xcode8.3  # OSX 10.12

# download and extract Sage
#
before_install:
  - cd ${HOME}
  - wget ${SAGE_SERVER}/${SAGE_TARBALL}
  - tar xjf ${HOME}/${SAGE_TARBALL}
  - cd ${TRAVIS_BUILD_DIR}

install: ${SAGE} setup.py build_ext --inplace

script: ${SAGE} runtests.py -v

addons:
  apt:
    packages:
     - gfortran

notifications:
  email: false
